# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cf9684cbe3f6d4d83e268c7f0a7343b43acb2d2174488966a989d2b6ec05911f8fb4e6d364abf5a2e004a0e75a7e9fea0cfa9d444618a3ad7c45fe1c790b067

test:
  secret_key_base: eb44825e04f832f449ef4c327172762fb5af8a7a024d080d23ddc2a1bd31d0cd52d8ccc63652f909ff511ce3c2ba39769a2fb7a2ded8b0f16999e02a402b1785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
